'use client';

import { useEffect, useState } from 'react';
import { useAuth } from '@/lib/auth-context';
import { apiFetch, ApiError } from '@/lib/api-client';
import { PageHeader, EmptyState } from '@/components/ui/page-header';

interface MySection { id: string; course: { title: string; code: string }; enrolledCount: number; }
interface FeedbackSummary { count: number; average: number | null; comments: (string | null)[]; }

export default function TeacherFeedbackPage() {
  const { accessToken, profile } = useAuth();
  const [sections, setSections] = useState<MySection[]>([]); const [sectionId, setSectionId] = useState('');
  const [summary, setSummary] = useState<FeedbackSummary | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { if (!accessToken || !profile?.teacherId) return; apiFetch<MySection[]>(`/teachers/${profile.teacherId}/sections`, { token: accessToken }).then((d) => { setSections(d); setSectionId(d[0]?.id ?? ''); }).catch((e) => setError(e instanceof ApiError ? e.message : 'Failed to load sections')); }, [accessToken, profile?.teacherId]);
  useEffect(() => { if (!sectionId || !accessToken) { setSummary(null); return; } setLoading(true); setError(null); apiFetch<FeedbackSummary>(`/feedback/section/${sectionId}`, { token: accessToken }).then(setSummary).catch((e) => setError(e instanceof ApiError ? e.message : 'Failed to load feedback')).finally(() => setLoading(false)); }, [sectionId, accessToken]);
  const current = sections.find((s) => s.id === sectionId); const comments = summary?.comments.filter((c): c is string => Boolean(c?.trim())) ?? []; const average = summary?.average ?? null;
  return <main className="min-w-0 overflow-x-hidden p-4 sm:p-6 lg:p-10">
    <PageHeader eyebrow="Course Evaluation" title="Section Feedback" subtitle="Review anonymized ratings and written comments from your students." />
    <section className="mb-6 rounded-2xl border border-slate-200/90 bg-white p-5 shadow-sm sm:p-6"><div className="max-w-3xl"><p className="mb-1 text-xs font-semibold uppercase tracking-[.12em] text-slate-500">Section</p><select value={sectionId} onChange={(e) => setSectionId(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-3 text-sm outline-none focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10">{sections.length === 0 && <option value="">No sections assigned</option>}{sections.map((s) => <option key={s.id} value={s.id}>{s.course.title} ({s.course.code}) · {s.enrolledCount} students</option>)}</select></div></section>
    {error && <div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    {loading ? <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">Loading feedback…</div> : summary ? <>
      <section className="mb-8 grid grid-cols-1 gap-4 md:grid-cols-[1.35fr_.8fr_.8fr]"><div className="rounded-2xl border border-slate-200/90 bg-slate-900 p-6 text-white shadow-sm"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-slate-400">Course</p><h2 className="mt-2 font-serif text-xl font-semibold">{current?.course.title ?? '—'}</h2><p className="mt-1 font-data text-xs text-slate-400">{current?.course.code ?? '—'}</p></div><div className="rounded-2xl border border-slate-200/90 bg-white p-6 shadow-sm"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-slate-400">Average rating</p><p className="mt-2 font-serif text-3xl font-semibold text-slate-900">{average === null ? '—' : average.toFixed(2)}</p><p className="mt-1 text-xs text-slate-400">out of 5</p></div><div className="rounded-2xl border border-slate-200/90 bg-white p-6 shadow-sm"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-slate-400">Responses</p><p className="mt-2 font-serif text-3xl font-semibold text-slate-900">{summary.count}</p><p className="mt-1 text-xs text-slate-400">anonymous submissions</p></div></section>
      {average !== null && <section className="mb-8 max-w-2xl rounded-2xl border border-slate-200/90 bg-white p-6 shadow-sm"><div className="flex items-end justify-between gap-4"><div><h2 className="font-serif text-lg font-semibold text-slate-900">Overall satisfaction</h2><p className="mt-1 text-sm text-slate-500">Average student rating for this section.</p></div><span className="font-data text-sm font-semibold text-slate-800">{average.toFixed(2)} / 5</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-900" style={{ width: `${Math.min(100, (average / 5) * 100)}%` }} /></div></section>}
      {comments.length === 0 ? <EmptyState title={summary.count ? 'No written comments' : 'No feedback yet'} hint={summary.count ? 'Students submitted ratings but did not leave written comments.' : 'Student evaluations will appear here when responses are submitted.'} /> : <section className="max-w-3xl"><div className="mb-4"><h2 className="font-serif text-lg font-semibold text-slate-900">Student comments</h2><p className="mt-1 text-sm text-slate-500">Comments are shown anonymously.</p></div><div className="space-y-3">{comments.map((comment, i) => <article key={i} className="rounded-2xl border border-slate-200/90 bg-white p-5 shadow-sm"><span className="block text-2xl leading-none text-slate-300">“</span><p className="mt-2 text-sm leading-7 text-slate-600">{comment}</p></article>)}</div></section>}
    </> : <EmptyState title="Select a section" hint="Choose one of your sections to review its student feedback." />}
  </main>;
}
